### ISSUE TITLE
Pacotes não usados.

### ISSUE THREAD

**Issue by weltoncastoldi** [jlnpinheiro/notifique-me-csharp#3]
Sua classe ficou muito boa... mas quando instalamos é instalado junto quase 200MB de outros pacotes que aparentemente nem são usados como: Globalizations Calendar, System.IO,  System.Net.Sockets e vários outros...

**Comment by jlnpinheiro** [comment]
Olá @weltoncastoldi !
Essas dependências são adicionadas em razão do projeto ser feito para o .NET Standard 2.0.

**Comment by jlnpinheiro** [comment]
@weltoncastoldi na verdade eu utilizava a versão 1.2 do .NET Standard. Criei a versão 3.1.0, utilizando agora a versão 2.0 do .NET Standard, removendo esse excesso de referências.
